name: Nightly Build

on:
  schedule:
    - cron: 0 12 * * *
  repository_dispatch:

jobs:
  buildtest:
    name: Test Build on ${{ matrix.os }} with JDK 11.0.4
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Checkout PhantomBot Repository
      uses: actions/checkout@v1
      with:
        repository: PhantomBot/PhantomBot
        ref: master 
    - name: Set up JDK 11.0.4
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.4
    - name: Set up Ant (Linux)
      run: sudo apt-get install ant
      if: startsWith(matrix.os, 'ubuntu-')
    - name: Set up Ant (Windows)
      run: choco install ant
      if: startsWith(matrix.os, 'windows-')
    - name: Set up Ant (macOS)
      run: |
        wget https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/ant.rb
        sed -i '' -e 's/www.apache.org\/dyn\/closer.cgi?path=/archive.apache.org\/dist\//g' ant.rb
        chmod +x ant.rb
        brew install ./ant.rb
        rm -f ant.rb
      if: startsWith(matrix.os, 'macOS-')
    - name: Build with Ant (Linux)
      if: startsWith(matrix.os, 'ubuntu-')
      run: ant -noinput -buildfile ${GITHUB_WORKSPACE}/../PhantomBot/build.xml test
    - name: Build with Ant (Windows)
      if: startsWith(matrix.os, 'windows-')
      run: ant -noinput -buildfile %GITHUB_WORKSPACE%/../PhantomBot/build.xml test
    - name: Build with Ant (macOS)
      if: startsWith(matrix.os, 'macOS-')
      run: ant -noinput -buildfile ${GITHUB_WORKSPACE}/../PhantomBot/build.xml test
  dryrun:
    name: Dry run on ubuntu-latest with JDK 11.0.4
    runs-on: ubuntu-latest
    needs: buildtest
    if: github.repository != 'PhantomBot/nightly-build'
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 1 
    - name: Set up JDK 11.0.4
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.4
    - name: Set up tools
      run: sudo apt-get install ant perl git zip coreutils
    - name: Dry Run Nightly Build
      env:
        DRY_RUN: 'true'
      run: |
        cd ${GITHUB_WORKSPACE}/scripts
        chmod 0744 ./nightlyPBBuild.sh
        ./nightlyPBBuild.sh
  build:
    name: Build and push on ubuntu-latest with JDK 11.0.4
    runs-on: ubuntu-latest
    needs: buildtest
    if: github.repository == 'PhantomBot/nightly-build'
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 1 
    - name: Set up JDK 11.0.4
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.4
    - name: Set up tools
      run: sudo apt-get install ant perl git zip coreutils
    - name: Build and Push Nightly Build
      env:
        TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        DRY_RUN: 'false'
      run: |
        cd ${GITHUB_WORKSPACE}/scripts
        chmod 0744 ./nightlyPBBuild.sh
        ./nightlyPBBuild.sh
